### ISSUE TITLE
Resulting Subgraphs contain edges which are not present in Input graphs

### ISSUE THREAD

**Issue by Bhuvanamitra** [TonyZZX/gSpan.Java#1]
I have run the code with default configurations and it results in subgraphs with edges which input graphs does not have. Is there any configuration change that I am missing? or Is there any argument required to avoid these subgraphs? I have tried both java and python version of gSpan code, problem persists in both of them.

I have attached my inputFile.txt and resultFile.txt for reference.
[resultFile.txt](https://github.com/TonyZZX/gSpan.Java/files/2614294/resultFile.txt)

[inputFile.txt](https://github.com/TonyZZX/gSpan.Java/files/2614292/inputFile.txt)

**Comment by TonyZZX** [comment]
The third column in v means the label of nodes. All nodes in your input have the same label, which means they can be treated as the same, so it makes sense the result will have "nonexistent" edges which are actually the old edges changed the node denotations.

**Comment by Bhuvanamitra** [comment]
Thanks for reply, But the problem is present even if I give different labels to nodes and edges. 
I have taken a part of your test data and gave to test, It also gave 'unknown' or 'nonexistent' edges. 
<<gspan.run(reader, writer, 1, 6, 4);>>
This is how I triggered the gspan algorithm from my java code. 
Can you please tell me what is going wrong here.

**Comment by TonyZZX** [comment]
Could you provide modified test data and the output? Thank you.

**Comment by Bhuvanamitra** [comment]
Sorry, My bad, I interpretted the result in wrong way. But one issue which i am facing is, i have graphs which are NOT LABELLED. Thats why i gave label 1 to all of them. Is this okay to give like this? or How to deal with Directed and UNLABELLED graphs..?? Thank You.

**Comment by TonyZZX** [comment]
Sorry, it seems like gSpan is not the best solution fitting in your problem.
